server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE/
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: FEEDBACK-SERVICE
          uri: lb://FEEDBACK-SERVICE/
          predicates:
            - Path=/feedback/**
          filters:
                - AuthenticationFilter
        - id: QUESTION-SERVICE
          uri: lb://QUESTION-SERVICE/
          predicates:
            - Path=/api/question/**
          filters:
            - AuthenticationFilter
        - id: ANSWER-SERVICE
          uri: lb://ANSWER-SERVICE/
          predicates:
            - Path=/answer/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
jwt:
  secret: testing
  validity: 20
  authDisabled: true